name: ML Pipeline (Prepare and Train)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-and-train:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Préparation des données
      - name: Prepare data
        run: |
          python main.py --step prepare --data data/data_churn.csv

      # Étape 5 : Entraînement du modèle
      - name: Train model
        run: |
          python main.py --step train
