name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install xgboost  # Installation explicite de xgboost au cas où il manque dans requirements.txt
        pip install lifelines  # Installation explicite de lifelines

    # Run linting with mypy
    - name: Run linting
      run: |
        . venv/bin/activate
        mypy --ignore-missing-imports --exclude venv .

    # Run formatting check with black
    - name: Run black formatting check
      run: |
        . venv/bin/activate
        black --check .

    # Run unit tests with pytest
    - name: Run tests with pytest
      run: |
        . venv/bin/activate
        pytest --maxfail=1 --disable-warnings -q

    # Prepare data
    - name: Prepare data
      run: |
        . venv/bin/activate
        python main.py --step prepare --data data_churn.csv

    # Train the model
    - name: Train the model
      run: |
        . venv/bin/activate
        python main.py --step train

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}

    # Optionally, you can deploy or run additional actions if needed
    # Example: Deploy to a server or Kubernetes cluster
    # - name: Deploy application
    #   run: |
    #     # Add your deployment commands here
